kind: pipeline
type: docker
name: default

steps:
  - name: gradle-build
    image: azul/zulu-openjdk:17
    commands:
      - ./gradlew build --no-daemon
    volumes:
      - name: gradle-cache
        path: /root/.gradle


  - name: gradle-test
    image: azul/zulu-openjdk:17
    commands:
      - ./gradlew test --no-daemon
    depends_on:
      - gradle-build
    volumes:
      - name: gradle-cache
        path: /root/.gradle


  - name: gradle-check
    image: azul/zulu-openjdk:17
    commands:
      - ./gradlew check --no-daemon
    depends_on:
      - gradle-build
    volumes:
      - name: gradle-cache
        path: /root/.gradle