package de.phyrone.buildscripts

import org.gradle.api.JavaVersion

const val WRITE_YOURSELF_TASK_GROUP = "write-yourself"

const val PROJ_COMMON_KOTLIN_JVM_TARGET = 8
const val PROJ_COMMON_KOTLIN_JVM_TARGET_STRING = "1.8"
val PROJ_COMMON_JAVA_VERSION = JavaVersion.VERSION_1_8



const val PROJ_CLIENT_KOTLIN_JVM_TARGET = 8
const val PROJ_CLIENT_KOTLIN_JVM_TARGET_STRING = "1.8"
val PROJ_CLIENT_JAVA_VERSION = JavaVersion.VERSION_1_8
val PROJ_CLIENT_ANDROID_COMPILE_SDK = 33

const val PROJ_SERVER_KOTLIN_JVM_TARGET = 11
const val PROJ_SERVER_KOTLIN_JVM_TARGET_STRING = "11"
val PROJ_SERVER_JAVA_VERSION = JavaVersion.VERSION_11