name: Commit Server

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request: {}

jobs:
  build_server:
    strategy:
      matrix:
        JVM_VERSION:
          - 11
          - 17
          - 20
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.JVM_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.JVM_VERSION }}
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - name: Check with Gradle
        run: ./gradlew check
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests with Gradle
        run: ./gradlew test
      - name: Stop Gradle Daemon
        run: ./gradlew --stop
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server
          if-no-files-found: error
          path: | 
            server/build/libs/*.jar
  build_client_web:
    name: Build Client Web      
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: client-web
          if-no-files-found: error
          path: | 
            client/dist
      

  build_client_tauri:
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
          working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      # get the build artifacts from the previous job
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add Arm64 target
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './client/src-tauri -> target'
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Build 
        if: matrix.platform != 'macos-latest'
        run: yarn tauri build
      - name: Build (macos universal)
        if: matrix.platform == 'macos-latest'
        run: yarn tauri build --target universal-apple-darwin
      #TODO: linux, windows arm64 support