name: Commit Server

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        JVM_VERSION:
          - 11
          - 17
          - 20
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.JVM_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.JVM_VERSION }}
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - name: Check with Gradle
        run: ./gradlew check
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests with Gradle
        run: ./gradlew test
      - name: Stop Gradle Daemon
        run: ./gradlew --stop
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: | 
            server/build/libs/*.jar
